/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------
    CycleDetailsListModel.h file handles cycle details list model container includes :
    cycle counts, date and time.
--------------------------- REVISION HISTORY ------------------------------
    rev1: 11/10/2023 - Initial version.
***************************************************************************/
#ifndef CYCLEDETAILSLIST_H
#define CYCLEDETAILSLIST_H

#include <QObject>
#include <QAbstractListModel>
#include "CycleDetailsListData.h"

class CycleDetailsListModel : public QAbstractListModel
{
    Q_OBJECT
public:
    enum CycleRoles {
        IndexRole = Qt::UserRole + 1,
        CycleNoRole,
        CycleDateRole,
        CycleTimeRole
    };
public:
    explicit CycleDetailsListModel(QObject *parent = nullptr);
    ~CycleDetailsListModel();

    int rowCount(const QModelIndex &parent = QModelIndex()) const override;
    QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const override;
    QModelIndex index(int row, int column, const QModelIndex &index = QModelIndex()) const override;

    Q_INVOKABLE void LoadCycleDetailsList();
protected:
    QHash<int, QByteArray> roleNames() const override;

private:
    QList<CycleDetailsListData*> m_ListData;
    void ClearCycleDetailsList();
    void AddNewCycleDetailsList(CycleDetailsListData *CycleDetailsList);

    /*Slot to be called when data update signal generated by communication thread*/
private slots:
    void OnCycleDetailsListUpdated();
};
#endif // CYCLEDETAILSLIST_H
