/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2024

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

--------------------------- MODULE DESCRIPTION ----------------------------
 Declares Alarm parameters implementation.

--------------------------- REVISION HISTORY ------------------------------
 rev1: 06/06/2024 -  Initial version.

***************************************************************************/

#include "AlarmLogStructure.h"

/*Initialization of Alarm name parameters*/
const std::map <ALARM_IDS, std::tuple<ALARM_SUBCATEGORY, std::string, std::string, std::string>> AlarmParamMap =
{
	//Alarm Identifier, 		Alarm Subcategory, Error Type, Description, Reason
	{ALARM_PHASE_OVERLOAD_OVA, {ALARM_SUBCAT,"Phase Overload","Phase Overload occurred during the weld","N/A"}},
	{ALARM_CURR_OVERLOAD_OVA,  {ALARM_SUBCAT,"Current Overload","Current Overload occurred during the weld","N/A"}},
	{ALARM_FREQ_OVERLOAD_OVA,  {ALARM_SUBCAT,"Frequency Overload","Frequency Overload occurred during the weld","N/A"}},	
	{ALARM_POWER_OVERLOAD_OVA, {ALARM_SUBCAT,"Power Overload","Power Overload occurred during the weld","N/A"}},
	{ALARM_VOLT_OVERLOAD_OVA,  {ALARM_SUBCAT,"Voltage Overload","Voltage Overload occurred during the weld","N/A"}},
	{ALARM_TEMP_OVERLOAD_OVA,  {ALARM_SUBCAT,"Temperature Overload","Temperature Overload occurred during the weld","N/A"}},
	
	{ALARM_EB_PHASE_OVERLOAD_OVA, {ALARM_SUBCAT,"Phase Overload","Phase Overload occurred during Energy Braking","N/A"}},
	{ALARM_EB_CURR_OVERLOAD_OVA,  {ALARM_SUBCAT,"Current Overload","Current Overload occurred during Energy Braking","N/A"}},
	{ALARM_EB_FREQ_OVERLOAD_OVA,  {ALARM_SUBCAT,"Frequency Overload","Frequency Overload occurred during Energy Braking","N/A"}},	
	{ALARM_EB_POWER_OVERLOAD_OVA, {ALARM_SUBCAT,"Power Overload","Power Overload occurred during Energy Braking","N/A"}},
	{ALARM_EB_VOLT_OVERLOAD_OVA,  {ALARM_SUBCAT,"Voltage Overload","Voltage Overload occurred during Energy Braking","N/A"}},
	{ALARM_EB_TEMP_OVERLOAD_OVA,  {ALARM_SUBCAT,"Temperature Overload","Temperature Overload occurred during Energy Braking","N/A"}},

	{ALARM_AB_PHASE_OVERLOAD_OVA, {ALARM_SUBCAT,"Phase Overload","Phase Overload occurred during Afterburst","N/A"}},
	{ALARM_AB_CURR_OVERLOAD_OVA,  {ALARM_SUBCAT,"Current Overload","Current Overload occurred during Afterburst","N/A"}},
	{ALARM_AB_FREQ_OVERLOAD_OVA,  {ALARM_SUBCAT,"Frequency Overload","Frequency Overload occurred during Afterburst","N/A"}},	
	{ALARM_AB_POWER_OVERLOAD_OVA, {ALARM_SUBCAT,"Power Overload","Power Overload occurred during Afterburst","N/A"}},
	{ALARM_AB_VOLT_OVERLOAD_OVA,  {ALARM_SUBCAT,"Voltage Overload","Voltage Overload occurred during Afterburst","N/A"}},
	{ALARM_AB_TEMP_OVERLOAD_OVA,  {ALARM_SUBCAT,"Temperature Overload","Temperature Overload occurred during Afterburst","N/A"}},
	
	{ALARM_POST_SEEK_PHASE_OVERLOAD_OVA, {ALARM_SUBCAT,"Phase Overload","Phase Overload occurred during Post Weld Seek","N/A"}},
	{ALARM_POST_SEEK_CURR_OVERLOAD_OVA,  {ALARM_SUBCAT,"Current Overload","Current Overload occurred during Post Weld Seek","N/A"}},
	{ALARM_POST_SEEK_FREQ_OVERLOAD_OVA,  {ALARM_SUBCAT,"Frequency Overload","Frequency Overload occurred during Post Weld Seek","N/A"}},	
	{ALARM_POST_SEEK_POWER_OVERLOAD_OVA, {ALARM_SUBCAT,"Power Overload","Power Overload occurred during Post Weld Seek","N/A"}},
	{ALARM_POST_SEEK_VOLT_OVERLOAD_OVA,  {ALARM_SUBCAT,"Voltage Overload","Voltage Overload occurred during Post Weld Seek","N/A"}},
	{ALARM_POST_SEEK_TEMP_OVERLOAD_OVA,  {ALARM_SUBCAT,"Temperature Overload","Temperature Overload occurred during Post Weld Seek","N/A"}},

	{ALARM_GND_DETECT_CMA, 			{ALARM_SUBCAT, "Ground Detect Abort", "The Ground Detect Input has become active and the Cycle has been aborted.","N/A"}}, 
	{ALARM_SONICS_MAX_CMA, 			{ALARM_SUBCAT, "Max Weld Time Exceeded", "The maximum time allowed for Ultrasonic energy to be applied to the part has been reached.","N/A"}},
	{ALARM_NO_AMPLITUDE_STEP_CMA, 	{WARNING_SUBCAT, "No Amplitude Step", "The amplitude step trigger was not reached.","N/A"}},
	{ALARM_NO_PRESSURE_STEP_CMA, 	{WARNING_SUBCAT, "No Pressure Step", "The pressure step trigger was not reached.","N/A"}},

	{ALARM_TRIGGER_LOST_WRA, 		{WARNING_SUBCAT, "Trigger Force lost in Weld", "The applied Force dropped below the minimum Trigger Force during the Weld Cycle.","N/A"}},
	{ALARM_TRIGGER_LOST_HOLD, 		{WARNING_SUBCAT, "Trigger Force lost in Hold", "The applied Force dropped below the minimum Trigger Force during the Hold.","N/A"}},
	{ALARM_ACTUATOR_CLEAR_WRA, 		{WARNING_SUBCAT, "Actuator clear not reached", "ULS is active and the actuator clear condition has not been met.","N/A"}},
	{ALARM_PEAK_POWER_CUTOFF_WRA,	{ALARM_SUBCAT, "Peak Power Cutoff", "The Peak Power Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_ABSOLUTE_CUTOFF_WRA,   	{ALARM_SUBCAT, "Absolute Distance Cutoff", "The Absolute Distance Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_ACTUATOR_CAL_WRA,   		{WARNING_SUBCAT, "Actuator Recalibration suggested", "No Description available","N/A"}},

	{ALARM_COLLAPSE_CUTOFF_WRA,   		{ALARM_SUBCAT, "Collapse Distance Cutoff", "The Collapse Distance Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_SONICS_DISABLE_WRA, 			{WARNING_SUBCAT, "Ultrasonics disabled", "The Ultrasonics Disable user input has been enabled during this cycle.","N/A"}},
	{ALARM_USB_MEM_FULL_WRA, 			{WARNING_SUBCAT, "USB Memory Nearly Full (80%)", "USB memory is greater than 80% Full. Please consider extracting data to an external storage drive to avoid loss of data.","N/A"}},
	{ALARM_DISK_MEM_FULL_WRA, 			{WARNING_SUBCAT, "Internal Storage Capacity Warning", "Internal Storage is greater than 80% Full. Please consider extracting data to USB to avoid loss of data.","N/A"}},
	{ALARM_FREQUENCY_LOW_CUTOFF_WRA, 	{ALARM_SUBCAT, "Frequency Low Cutoff", "The Frequency Low Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_FREQUENCY_HIGH_CUTOFF_WRA,	{ALARM_SUBCAT, "Frequency High Cutoff", "The Frequency High Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_ENERGY_CUTOFF_WRA, 			{ALARM_SUBCAT, "Energy Cutoff", "The Energy Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_GND_DETECT_CUTOFF_WRA, 		{ALARM_SUBCAT, "Ground Detect Cutoff", "The Ground Detect Cutoff has triggered during the weld.","N/A"}},
	{ALARM_TIME_CUTOFF_WRA, 			{ALARM_SUBCAT, "Time Cutoff", "The Time Cutoff value has been exceeded during the weld.","N/A"}},
	{ALARM_MIN_ENERGY_COMPENSATION, 	{ALARM_SUBCAT, "Min Energy Compensation", "Minimum Energy Compensation value not reached during weld","N/A"}},
	{ALARM_MAX_ENERGY_COMPENSATION, 	{ALARM_SUBCAT, "Max Energy Compensation", "Maximum Energy Compensation value exceeded during weld","N/A"}},
	{ALARM_RTC_LOW_BATT_WRA, 			{WARNING_SUBCAT, "RTC Low Battery", "System time may not be reliable. Set system time.","N/A"}},
	{ALARM_ALARM_LOG_FULL_WRA, 			{WARNING_SUBCAT, "Alarm Log Capacity Warning", "Alarm Log Storage is greater than 80% Full.","N/A"}},
	{ALARM_EVENT_LOG_FULL_WRA, 			{WARNING_SUBCAT, "Event Log Capacity Warning", "Event Log Storage is greater than 80% Full.","N/A"}},
	{ALARM_WELD_RESULT_FULL_WRA, 		{WARNING_SUBCAT, "Weld Result Capacity Warning", "Weld Result Storage is greater than 80% Full.","N/A"}},
	{ALARM_WELD_GRAPH_FULL_WRA, 		{WARNING_SUBCAT, "Weld Graph Capacity Warning", "Weld Graph Storage is greater than 80% Full.","N/A"}},
	{ALARM_HORN_SCAN_FULL_WRA, 			{WARNING_SUBCAT, "Horn Scan Graph Capacity Warning", "Horn Scan Graph Storage is greater than 80% Full.","N/A"}},
	
	{ALARM_VELOCITY_LIMIT_MLR_PRA, 		{ALARM_SUBCAT, "-Velocity Reject Limit", "The Velocity did not exceed the lower limit value.","N/A"}},
	{ALARM_VELOCITY_LIMIT_PLR_PRA, 		{ALARM_SUBCAT, "+Velocity Reject Limit", "The Velocity exceeded the upper limit value.","N/A"}},
	{ALARM_PEAKPOWER_LIMIT_MLR_PRA, 	{ALARM_SUBCAT, "-Peak Power Reject Limit", "The Peak Power did not exceed the lower limit value.","N/A"}},
	{ALARM_PEAKPOWER_LIMIT_PLR_PRA, 	{ALARM_SUBCAT, "+Peak Power Reject Limit", "The Peak Power exceeded the upper limit value.","N/A"}},
	{ALARM_TIME_LIMIT_MLR_PRA, 			{ALARM_SUBCAT, "-Time Reject Limit", "The total Weld Time did not exceed the lower limit value.","N/A"}},
	{ALARM_TIME_LIMIT_PLR_PRA, 			{ALARM_SUBCAT, "+Time Reject Limit", "The total Weld Time exceeded the upper limit value.","N/A"}},
	{ALARM_ENERGY_LIMIT_MLR_PRA, 		{ALARM_SUBCAT, "-Energy Reject Limit", "The total Weld Energy did not exceed the lower limit value.","N/A"}},
	{ALARM_ENERGY_LIMIT_PLR_PRA, 		{ALARM_SUBCAT, "+Energy Reject Limit", "The total Weld Energy exceeded the upper limit value.","N/A"}},
	{ALARM_COLLAPSEDIST_LIMIT_MLR_PRA, 	{ALARM_SUBCAT, "-Collapse Distance Reject Limit", "The total Collapse Distance did not exceed the lower limit value.","N/A"}},
	{ALARM_COLLAPSEDIST_LIMIT_PLR_PRA, 	{ALARM_SUBCAT, "+Collapse Distance Reject Limit", "The total Collapse Distance exceeded the upper limit value.","N/A"}},
	{ALARM_ABSOLUTEDIST_LIMIT_MLR_PRA, 	{ALARM_SUBCAT, "-Absolute Distance Reject Limit", "The total Absolute Distance did not exceed the lower limit value.","N/A"}},
	{ALARM_ABSOLUTEDIST_LIMIT_PLR_PRA, 	{ALARM_SUBCAT, "+Absolute Distance Reject Limit", "The total Absolute Distance exceeded the upper limit value.","N/A"}},
	{ALARM_TRIGGERDIST_LIMIT_MLR_PRA, 	{ALARM_SUBCAT, "-Trigger Reject Limit", "The Trigger Distance did not exceed the lower limit value.","N/A"}},
	{ALARM_TRIGGERDIST_LIMIT_PLR_PRA, 	{ALARM_SUBCAT, "+Trigger Reject Limit", "The Trigger Distance exceeded the upper limit value.","N/A"}},
	{ALARM_WELDFORCE_LIMIT_MLR_PRA, 	{ALARM_SUBCAT, "-Weld Force Reject Limit", "The total Weld Force did not exceed the lower limit value.","N/A"}},
	{ALARM_WELDFORCE_LIMIT_PLR_PRA, 	{ALARM_SUBCAT, "+Weld Force Reject Limit", "The total Weld Force exceeded the upper limit value.","N/A"}},
	{ALARM_FREQUENCY_LIMIT_MLR_PRA,		{ALARM_SUBCAT, "-Frequency Reject Limit", "The Weld Frequency did not exceed the lower limit value.","N/A"}},
	{ALARM_FREQUENCY_LIMIT_PLR_PRA, 	{ALARM_SUBCAT, "+Frequency Reject Limit", "The Weld Frequency exceeded the upper limit value.","N/A"}},
	
	{ALARM_ENERGY_LIMIT_MLS_PSA, 		{WARNING_SUBCAT, "-Energy Suspect Limit", "The total Weld Energy did not exceed the lower limit value.","N/A"}},
	{ALARM_ENERGY_LIMIT_PLS_PSA, 		{WARNING_SUBCAT, "+Energy Suspect Limit", "The total Weld Energy exceeded the upper limit value.","N/A"}},
	{ALARM_PEAKPOWER_LIMIT_MLS_PSA, 	{WARNING_SUBCAT, "-Peak Power Suspect Limit", "The Peak Power did not exceed the lower limit value.","N/A"}},
	{ALARM_PEAKPOWER_LIMIT_PLS_PSA, 	{WARNING_SUBCAT, "+Peak Power Suspect Limit", "The Peak Power exceeded the upper limit value.","N/A"}},

	{ALARM_COLLAPSEDIST_LIMIT_MLS_PSA, 	{WARNING_SUBCAT, "-Collapse Distance Suspect Limit", "The total Collapse Distance did not exceed the lower limit value.","N/A"}},
	{ALARM_COLLAPSEDIST_LIMIT_PLS_PSA,	{WARNING_SUBCAT, "+Collapse Distance Suspect Limit", "The total Collapse Distance exceeded the upper limit value.","N/A"}},
	{ALARM_ABSOLUTEDIST_LIMIT_MLS_PSA, 	{WARNING_SUBCAT, "-Absolute Distance Suspect Limit", "The total Absolute Distance did not exceed the lower limit value.","N/A"}},
	{ALARM_ABSOLUTEDIST_LIMIT_PLS_PSA, 	{WARNING_SUBCAT, "+Absolute Distance Suspect Limit", "The total Absolute Distance exceeded the upper limit value.","N/A"}},
	{ALARM_TRIGGERDIST_LIMIT_MLS_PSA, 	{WARNING_SUBCAT, "-Trigger Distance Suspect Limit", "The Trigger Distance did not exceed the lower limit value.","N/A"}},
	{ALARM_TRIGGERDIST_LIMIT_PLS_PSA, 	{WARNING_SUBCAT, "+Trigger Distance Suspect Limit", "The Trigger Distance exceeded the upper limit value.","N/A"}},
	{ALARM_WELDFORCE_LIMIT_MLS_PSA, 	{WARNING_SUBCAT, "-Weld Force Suspect Limit", "The Weld Force did not exceed the lower limit value.","N/A"}},
	{ALARM_WELDFORCE_LIMIT_PLS_PSA, 	{WARNING_SUBCAT, "+Weld Force Suspect Limit", "The Weld Force exceeded the upper limit value.","N/A"}},
	{ALARM_TIME_LIMIT_MLS_PSA, 			{WARNING_SUBCAT, "-Time Suspect Limit", "The Time did not exceed the lower limit value.","N/A"}},
	{ALARM_TIME_LIMIT_PLS_PSA, 			{WARNING_SUBCAT, "+Time Suspect Limit", "The Time exceeded the upper limit value.","N/A"}},
	{ALARM_VELOCITY_LIMIT_MLS_PSA,		{WARNING_SUBCAT, "-Velocity Suspect Limit", "The total Weld Velocity did not exceed the lower limit value.","N/A"}},
	{ALARM_VELOCITY_LIMIT_PLS_PSA, 		{WARNING_SUBCAT, "+Velocity Suspect Limit", "The total Weld Velocity exceeded the upper limit value.","N/A"}},
	{ALARM_FREQUENCY_LIMIT_MLS_PSA, 	{WARNING_SUBCAT, "-Frequency Suspect Limit", "The Weld Frequency did not exceed the lower limit value.","N/A"}},
	{ALARM_FREQUENCY_LIMIT_PLS_PSA, 	{WARNING_SUBCAT, "+Frequency Suspect Limit", "The Weld Frequency exceeded the upper limit value.","N/A"}},

	{ALARM_START_SWITCH_CLOSED_EFA, 	{NOTIFICATION_SUBCAT, "Start Switch Still Active", "The Start Switches are still active 6 seconds after the end of the Cycle.","N/A"}},
	{ALARM_ULS_STILL_ACTIVE_EFA, 		{ALARM_SUBCAT, "ULS Still Active", "The ULS has not become inactive after Trigger or Pretrigger has been reached.","N/A"}},
	{ALARM_ULS_NOT_ACTIVE_HOME_EFA, 	{ALARM_SUBCAT, "ULS Not Active After Homing", "The ULS is not active after an E-Stop or Alarm.","N/A"}},
	{ALARM_GND_DETECT_EFA, 				{WARNING_SUBCAT, "Ground Detect Before Trigger", "The Ground Detect Input has become active before Trigger occurred.","N/A"}},
	{ALARM_START_SWITCH_LOST_EFA, 		{NOTIFICATION_SUBCAT, "Start Switch Lost", "The Start Switches became inactive before Trigger occurred.","N/A"}},
	{ALARM_ALARM_LOG_FULL_EFA,			{ALARM_SUBCAT, "Alarm Log Capacity Reached", "Alarm Log Storage is Full.","N/A"}},
	{ALARM_EVENT_LOG_FULL_EFA, 			{ALARM_SUBCAT, "Event Log Capacity Reached", "Event Log Storage is Full.","N/A"}},
	{ALARM_WELD_RESULT_FULL_EFA, 		{ALARM_SUBCAT, "Weld Result Capacity Reached", "Weld Result Storage is Full.","N/A"}},
	{ALARM_WELD_GRAPH_FULL_EFA, 		{ALARM_SUBCAT, "Weld Graph Capacity Reached", "Weld Graph Storage is Full.","N/A"}},
	{ALARM_HORN_SCAN_FULL_EFA, 			{ALARM_SUBCAT, "Horn Scan Graph Capacity Reached", "Horn Scan Graph Storage is Full.","N/A"}},
	{ALARM_PRETRIGGER_TIMEOUT_EFA, 		{ALARM_SUBCAT, "Pretrigger Timeout", "Pretrigger has not occurred within 10 seconds of ULS going inactive.","N/A"}},
	{ALARM_DATA_ERROR_EFA, 				{ALARM_SUBCAT, "Data Error"	, "Corrupted data in the Recipe checked at power up.","N/A"}},
	{ALARM_ACTUATOR_RETURN_TIMEOUT_EFA, {ALARM_SUBCAT, "Actuator Return Timeout", "The carriage has not returned home in 4 seconds","N/A"}},
	{ALARM_ACTUATOR_NOVRAM_EFA, 		{ALARM_SUBCAT, "Actuator NOVRAM", "The actuator NOVRAM has corrupted data. This is checked at power up.","N/A"}},
	{ALARM_PS_NOVRAM_EFA, 				{ALARM_SUBCAT, "P/S NOVRAM", "The power supply NOVRAM has corrupted data. This is checked at power up.","N/A"}},
	{ALARM_START_SWITCH_TIME_EFA, 		{NOTIFICATION_SUBCAT, "Start Switch Time", "Both Start Switches were not pressed within the allowed time frame.","N/A"}},
	{ALARM_DISK_MEM_FULL_EFA, 			{ALARM_SUBCAT, "Data Storage Full", "Internal Storage Device is full. Any operation which requires Data Storage will not be allowed.","N/A"}},
	{ALARM_INTERNAL_STORAGE_FAILURE_EFA,{ALARM_SUBCAT, "Internal Storage Failure", "Contact Branson Service for Assistance.","N/A"}},
	{ALARM_RECALIBRATE_ACTUATOR_EFA, 	{ALARM_SUBCAT, "Recalibrate Actuator", "The force calibration values loaded into the system are invalid.","N/A"}},
	{ALARM_ACTUATOR_CLEAR_FUNC_EFA, 	{NOTIFICATION_SUBCAT, "Actuator Clear Function", "ULS is active before actuator clear condition was met.","N/A"}},
	{ALARM_EXT_DISK_NA_EFA, 			{WARNING_SUBCAT, "External Tooling Active", "The External Tooling Input has not become inactive for more than 4 seconds after the end of a cycle.","N/A"}},
	{ALARM_ACTUATOR_TYPE_CHANGED_EFA, 	{ALARM_SUBCAT, "Actuator Type Changed", "The actuator type detected at power up is different from power down or after an E-Stop.","N/A"}},
	{ALARM_SYS_PRESSURE_INCORRECT_EFA, 	{ALARM_SUBCAT, "System Pressure Incorrect", "The set air pressure is not achieved.","N/A"}},
	{ALARM_PART_PRESENT_ACTIVE_EFA, 	{WARNING_SUBCAT, "Part Present Active", "The Part Present Input is configured and is still active for more than 4 seconds after the end of a cycle.","N/A"}},
	{ALARM_INTERNAL_COMM_USB_EFA, 		{ALARM_SUBCAT, "USB Memory Lost", "The USB memory stick has been removed or is not functional. Since weld data was configured to be saved on the USB stick welding must be stopped until either the USB stick is functional or weld data is no longer required to be saved.","N/A"}},
	{ALARM_INTERNAL_COMM_NFS_EFA, 		{ALARM_SUBCAT, "NFS Mounting Fail", "NFS is not functional. Since weld data was configured to be saved on the NFS welding must be stopped until either the NFS is functional or weld data is no longer required to be saved.","N/A"}},
	{ALARM_INTERNAL_COMM_ENET, 			{NOTIFICATION_SUBCAT, "Connection Lost", "Communication between the HMI and the welder has been disconnected.","N/A"}},
	{ALARM_INTERNAL_COMM_LINK_LOST, 	{ALARM_SUBCAT, "Internal Communication Link Lost", "The internal communication link has been lost between the Supervisor and actuator","N/A"}},
	{ALARM_INTERNAL_COMM_CABLE_EFA, 	{ALARM_SUBCAT, "Cable Failure", "If Cable Detect is configured and the pin goes inactive.","N/A"}},
	{ALARM_PROF_ETHIP_NOT_RESP_EFA, 	{ALARM_SUBCAT, "PROFINET or EtherNet/IP not responding", "No Description available","N/A"}},
	{ALARM_SONICS_SOURCE_LOST_EFA, 		{ALARM_SUBCAT, "AC Line Voltage Lost", "230 V input to the Power Supply is not ON.","N/A"}},
	{ALARM_TRIG_ACTIVE_IN_READY_EFA, 	{ALARM_SUBCAT, "Trigger active in Ready", "Trigger force is detected in the Ready State.","N/A"}},
	{ALARM_INTERNAL_COMM_KEYPAD_LOST, 	{ALARM_SUBCAT, "Internal Keypad Bezel Communication Link Lost", "The internal communication link has been lost between the Supervisor and Keypad Bezel","N/A"}},

	{ALARM_SONICS_DELAY_TIMEOUT_NCA, 	{WARNING_SUBCAT, "External Sonics Delay Timeout", "Trigger Delay has been turned on, but the assigned input did not become inactive within the 30 seconds allowed.","N/A"}},
	{ALARM_PART_CONTACT_PRETRIGGER_NCA, {WARNING_SUBCAT, "Part Contact before Pretrigger", "The Part Contact Distance has been met before the defined Pretrigger Distance.","N/A"}},
	{ALARM_CYCLE_ABORT_NCA,             {ALARM_SUBCAT, "External Cycle Abort", "The Cycle Abort Digital Input has been activated.","N/A"}},
	{ALARM_ABSOLUTE_DISTANCE_NCA, 		{ALARM_SUBCAT, "Invalid Part Contact Distance", "The Part Contact Distance is invalid or not set","N/A"}},
	{ALARM_EXTERNAL_TOOLING_LOST_NCA, 	{ALARM_SUBCAT, "External Tooling Input Lost", "The External Tooling Input became inactive before Hold Time ended.","N/A"}},
	{ALARM_EXTERNAL_TOOLING_TIMEOUT_NCA,{ALARM_SUBCAT, "External Tooling Input Timeout", "The External Tooling Input did not become active within the Tooling Delay Input time after the External Tooling Output became active.","N/A"}},
	{ALARM_PART_PRESENT_LOST_NCA, 		{WARNING_SUBCAT, "Part Present Input Lost", "The Part Present Input became inactive before the end of Hold Time.","N/A"}},
	{ALARM_TRIGGER_TIMEOUT_NCA, 		{ALARM_SUBCAT, "Trigger Timeout", "Trigger has not occurred within 10 seconds of ULS going inactive.","N/A"}},
	{ALARM_READY_POSITION_TIMEOUT_NCA, 	{ALARM_SUBCAT, "Ready Position Timeout", "The Actuator did not return to the Ready Position within 4 seconds from end of Hold Time.","N/A"}},
	{ALARM_RECIPE_NOT_VALID_NCA, 		{ALARM_SUBCAT, "Recipe Not Valid", "The External Recipe # is not valid through the I/O or Barcode scanner.","N/A"}},

	{ALARM_POWER_SUPPLY_ASSYM_COMP_MISMATCH_NCA,{ALARM_SUBCAT, "Power Supply Assembly Component Mismatch", "The Power Supply Component Name defined in the System Configuration do not match the Name stored with this Recipe.","N/A"}},
	{ALARM_ACTUATOR_ASSYM_COMP_MISMATCH_NCA, 	{ALARM_SUBCAT, "Actuator Assembly Component Mismatch", "The Actuator Component Name defined in the System Configuration do not match the Name stored with this Recipe.","N/A"}},
	{ALARM_STACK_ASSYM_COMP_MISMATCH_NCA, 		{ALARM_SUBCAT, "Stack Assembly Component Mismatch", "The Ultrasonic Stack Component Name defined in the System Configuration do not match the Name stored with this Recipe.","N/A"}},
	{ALARM_BATCH_COUNT_NCA, 					{ALARM_SUBCAT, "Batch Count Complete", "The target number of welds for this Batch has been met. Navigate to the Recipe Production Screen to reset the count.","N/A"}},
	{ALARM_RECIPE_NOT_VALIDATED_NCA, 			{ALARM_SUBCAT, "Active Recipe not Validated", "The Operator is attempting to run a recipe that has not been Validated.","N/A"}},

	{ALARM_TEST_PHASE_OVERLOAD, {ALARM_SUBCAT,"Test-Phase Overload","Phase Overload occurred during Test","N/A"}},
	{ALARM_TEST_CURR_OVERLOAD,  {ALARM_SUBCAT,"Test-Current Overload","Current Overload occurred during Test","N/A"}},
	{ALARM_TEST_FREQ_OVERLOAD,  {ALARM_SUBCAT,"Test-Frequency Overload","Frequency Overload occurred during Test","N/A"}},	
	{ALARM_TEST_POWER_OVERLOAD, {ALARM_SUBCAT,"Test-Power Overload","Power Overload occurred during Test","N/A"}},
	{ALARM_TEST_VOLT_OVERLOAD,  {ALARM_SUBCAT,"Test-Voltage Overload","Voltage Overload occurred during Test","N/A"}},
	{ALARM_TEST_TEMP_OVERLOAD,  {ALARM_SUBCAT,"Test-Temperature Overload","Temperature Overload occurred during Test","N/A"}},

	{ALARM_PRETRG_PHASE_OVERLOAD, {ALARM_SUBCAT,"Pretrigger-Phase Overload","Phase Overload occurred during Pretrigger","N/A"}},
	{ALARM_PRETRG_CURR_OVERLOAD,  {ALARM_SUBCAT,"Pretrigger-Current Overload","Current Overload occurred during Pretrigger","N/A"}},
	{ALARM_PRETRG_FREQ_OVERLOAD,  {ALARM_SUBCAT,"Pretrigger-Frequency Overload","Frequency Overload occurred during Pretrigger","N/A"}},	
	{ALARM_PRETRG_POWER_OVERLOAD, {ALARM_SUBCAT,"Pretrigger-Power Overload","Power Overload occurred during Pretrigger","N/A"}},
	{ALARM_PRETRG_VOLT_OVERLOAD,  {ALARM_SUBCAT,"Pretrigger-Voltage Overload","Voltage Overload occurred during Pretrigger","N/A"}},
	{ALARM_PRETRG_TEMP_OVERLOAD,  {ALARM_SUBCAT,"Pretrigger-Temperature Overload","Temperature Overload occurred during Pretrigger","N/A"}},

	{ALARM_SEEK_PHASE_OVERLOAD, {ALARM_SUBCAT,"Seek-Phase Overload","Phase Overload occurred during Seek","N/A"}},
	{ALARM_SEEK_CURR_OVERLOAD,  {ALARM_SUBCAT,"Seek-Current Overload","Current Overload occurred during Seek","N/A"}},
	{ALARM_SEEK_FREQ_OVERLOAD,  {ALARM_SUBCAT,"Seek-Frequency Overload","Frequency Overload occurred during Seek","N/A"}},	
	{ALARM_SEEK_POWER_OVERLOAD, {ALARM_SUBCAT,"Seek-Power Overload","Power Overload occurred during Seek","N/A"}},
	{ALARM_SEEK_VOLT_OVERLOAD,  {ALARM_SUBCAT,"Seek-Voltage Overload","Voltage Overload occurred during Seek","N/A"}},
	{ALARM_SEEK_TEMP_OVERLOAD,  {ALARM_SUBCAT,"Seek-Temperature Overload","Temperature Overload occurred during Seek","N/A"}},

	{ALARM_PREWELD_SEEK_PHASE_OVERLOAD, {ALARM_SUBCAT,"Pre-Weld Seek-Phase Overload","Phase Overload occurred during Pre-Weld Seek","N/A"}},
	{ALARM_PREWELD_SEEK_CURR_OVERLOAD,  {ALARM_SUBCAT,"Pre-Weld Seek-Current Overload","Current Overload occurred during Pre-Weld Seek","N/A"}},
	{ALARM_PREWELD_SEEK_FREQ_OVERLOAD,  {ALARM_SUBCAT,"Pre-Weld Seek-Frequency Overload","Frequency Overload occurred during Pre-Weld Seek","N/A"}},	
	{ALARM_PREWELD_SEEK_POWER_OVERLOAD, {ALARM_SUBCAT,"Pre-Weld Seek-Power Overload","Power Overload occurred during Pre-Weld Seek","N/A"}},
	{ALARM_PREWELD_SEEK_VOLT_OVERLOAD,  {ALARM_SUBCAT,"Pre-Weld Seek-Voltage Overload","Voltage Overload occurred during Pre-Weld Seek","N/A"}},
	{ALARM_PREWELD_SEEK_TEMP_OVERLOAD,  {ALARM_SUBCAT,"Pre-Weld Seek-Temperature Overload","Temperature Overload occurred during Pre-Weld Seek","N/A"}},

	{ALARM_POSTWELD_SEEK_PHASE_OVERLOAD, {ALARM_SUBCAT,"Post-Weld Seek-Phase Overload","Phase Overload occurred during Post-Weld Seek","N/A"}},
	{ALARM_POSTWELD_SEEK_CURR_OVERLOAD,  {ALARM_SUBCAT,"Post-Weld Seek-Current Overload","Current Overload occurred during Post-Weld Seek","N/A"}},
	{ALARM_POSTWELD_SEEK_FREQ_OVERLOAD,  {ALARM_SUBCAT,"Post-Weld Seek-Frequency Overload","Frequency Overload occurred during Post-Weld Seek","N/A"}},	
	{ALARM_POSTWELD_SEEK_POWER_OVERLOAD, {ALARM_SUBCAT,"Post-Weld Seek-Power Overload","Power Overload occurred during Post-Weld Seek","N/A"}},
	{ALARM_POSTWELD_SEEK_VOLT_OVERLOAD,  {ALARM_SUBCAT,"Post-Weld Seek-Voltage Overload","Voltage Overload occurred during Post-Weld Seek","N/A"}},
	{ALARM_POSTWELD_SEEK_TEMP_OVERLOAD,  {ALARM_SUBCAT,"Post-Weld Seek-Temperature Overload","Temperature Overload occurred during Post-Weld Seek","N/A"}},

	{ALARM_ELC_NO_ALARM, 						{ALARM_SUBCAT,"EN Unknown Alarm","EN Unknown Alarm","N/A"}},
	{ALARM_ELC_LE_QEI_PHASE_ERROR, 				{ALARM_SUBCAT,"EN Linear Encoder Phase Error","EN Linear Encoder Phase Error is detected","N/A"}},
	{ALARM_ELC_LE_READY_QEI_MIN_DISTANCE_LIMIT, {ALARM_SUBCAT,"EN Linear Encoder minimum distance limit","EN Linear Encoder minimum distance limit is exceeded","N/A"}},
	{ALARM_ELC_LE_DRIVE_ON_QEI_POSITION_ERROR, 	{ALARM_SUBCAT,"EN Linear Encoder drive on position","EN Linear Encoder position is not changed during drive on","N/A"}},
	{ALARM_ELC_LE_QEI_NOT_ZERO_POSITION, 		{ALARM_SUBCAT,"EN Linear Encoder away position","EN Horn is at home position but Linear Encoder says at away position","N/A"}},
	{ALARM_ELC_LE_QEI_ZERO_POSITION, 			{ALARM_SUBCAT,"EN Linear Encoder home position","EN Horn is not in home position but Linear Encoder says at home position","N/A"}},
	{ALARM_ELC_PB_BOTH_DRV_ACTIVE_SAMETIME, 	{ALARM_SUBCAT,"EN Both Palm button Drives Active","EN Both palm button drives are active at same time","N/A"}},
	{ALARM_ELC_PB_EITHER_ONE_DRV_FAIL, 			{ALARM_SUBCAT,"EN Either one Palm button Drive Fail","EN Either one palm button drive is failed","N/A"}},
	{ALARM_ELC_PB_PB_PRESSED_POWER_UP, 			{ALARM_SUBCAT,"EN Palm button pressed during power up","EN Palm buttons are pressed during power up","N/A"}},
	{ALARM_ELC_PB_ONE_OR_BOTH_PB_PRESSED_PREREADY, 	{ALARM_SUBCAT,"EN Palm button pressed during pre-ready","EN Palm buttons are pressed during pre-ready","N/A"}},
	{ALARM_ELC_PB_ONLY_ONE_PB_PRESSED_READY, 	{ALARM_SUBCAT,"EN Only one Palm button pressed during ready","EN Only one palm button is pressed during ready","N/A"}},	
	{ALARM_ELC_PB_TWO_HAND_TIMING_NOT_SATISFIED_READY, {ALARM_SUBCAT,"EN Palm buttons two hand timing not satisfied","EN Palm buttons two hand timing is not satisfied during ready","N/A"}},
	{ALARM_ELC_PB_ONE_OR_BOTH_PB_RELEASED_DRIVEON, 	{ALARM_SUBCAT,"EN One or both Palm button released during drive on","EN One or both Palm button released during drive on","N/A"}},
	{ALARM_ELC_PB_STILL_PB_PRESSED_FAULT,			{ALARM_SUBCAT,"EN Palm button still pressed during fault","EN Palm button still pressed during fault","N/A"}},
	{ALARM_ELC_UFAIL24_SIGNAL_ERROR, 				{ALARM_SUBCAT,"EN UFail24 signal error","EN UFail24 signal error is detected","N/A"}},
	{ALARM_ELC_ESTOP_BUTTON_ERROR, 					{ALARM_SUBCAT,"EN EStop button error","EN Both EStop1 and Estop2 signals are same","N/A"}},
	{ALARM_ELC_ULS_SIGNAL_ERROR, 					{ALARM_SUBCAT,"EN Upper Limit Switch signal error","EN ULS is at home position and TRS is ON","N/A"}},
	{ALARM_ELC_SBEAM_FORCE_LIMIT, 					{ALARM_SUBCAT,"EN SBeam Force Limit","EN SBeam Force Limit is exceeded","N/A"}},
	{ALARM_ELC_TRS_SIGNAL_ERROR, 					{ALARM_SUBCAT,"EN Trigger Switch signal error","EN TRS is On and ULS is at home position","N/A"}},
	{ALARM_ELC_SVRELAY_RELAY_STATE_NOT_DRV, 		{ALARM_SUBCAT,"EN SVRelay state not drive","EN SV1 relay input status does not match with SV1_HI relay output","N/A"}},
	{ALARM_ELC_BOARD_MISMATCH, 						{ALARM_SUBCAT,"EN Board Mismatch fault","EN Board Mismatch is detected","N/A"}},
	{ALARM_ELC_SONICS_EN_SIGNAL_ERROR, 				{ALARM_SUBCAT,"EN Sonics enable signal error","EN Sonics enable signal error is detected","N/A"}},
	{ALARM_ELC_BIST_REGISTER_TEST_FAIL, 			{ALARM_SUBCAT,"EN BIST Register test fail","EN BIST Register test is failed","N/A"}},
	{ALARM_ELC_BIST_RAMSAFEAREA_TEST_FAIL, 			{ALARM_SUBCAT,"EN BIST RAM Safe Area test fail","EN BIST RAM Safe Area test is failed","N/A"}},
	{ALARM_ELC_BIST_PC_TEST_FAIL, 					{ALARM_SUBCAT,"EN BIST Program Counter test fail","EN BIST Program Counter test is failed","N/A"}},
	{ALARM_ELC_BIST_RAMDATAAREA_TEST_FAIL, 			{ALARM_SUBCAT,"EN BIST RAM Data Area test fail","EN BIST RAM Data Area test is failed","N/A"}},
	{ALARM_ELC_BIST_ADC_TEST_FAIL, 					{ALARM_SUBCAT,"EN BIST ADC test fail","EN BIST ADC test is failed","N/A"}},
	{ALARM_ELC_BIST_RAMSTACKAREA_TEST_FAIL, 		{ALARM_SUBCAT,"EN BIST RAM Stack Area test fail","EN BIST RAM Stack Area test is failed","N/A"}},
	{ALARM_ELC_BIST_FLASH_TEST1_FAIL, 				{ALARM_SUBCAT,"EN BIST Flash test1 fail","EN BIST Flash test1 is failed","N/A"}},
	{ALARM_ELC_BIST_FLASH_TEST2_FAIL, 				{ALARM_SUBCAT,"EN BIST Flash test2 fail","EN BIST Flash test2 is failed","N/A"}},
	{ALARM_ELC_BIST_FLASH_TEST3_FAIL, 				{ALARM_SUBCAT,"EN BIST Flash test3 fail","EN BIST Flash test3 is failed","N/A"}},
	{ALARM_ELC_BIST_FLASH_TEST4_FAIL, 				{ALARM_SUBCAT,"EN BIST Flash test4 fail","EN BIST Flash test4 is failed","N/A"}},
	{ALARM_ELC_INCORRECT_STATUS,					{ALARM_SUBCAT,"EN Incorrect Status","EN Incorrect alarm status is received","N/A"}},

	{ALARM_ELC_VARIANT_DETECTION_FAIL, 				{ALARM_SUBCAT,"AC Variant Detection Fail","AC Variant Detection is failed","N/A"}},
	{ALARM_ELC_LINEAR_ENCODER_FAULT,				{ALARM_SUBCAT,"AC Linear Encoder Fault","AC Linear Encoder fault is detected","N/A"}},
	{ALARM_ELC_PRESSURE_REGULATOR_FAULT, 			{ALARM_SUBCAT,"AC Pressure Regulator Fault","AC Pressure Regulator fault is detected","N/A"}},
	{ALARM_ELC_SAFETY_MICRO_FAULT, 					{ALARM_SUBCAT,"AC Safety Micro Communication Fault","AC Safety Micro commnunication fault is detected","N/A"}},
	{ALARM_ELC_AC_EEPROM_FAULT, 					{ALARM_SUBCAT,"AC EEPROM Fault","AC EEPROM fault is detected","N/A"}},
	{ALARM_ELC_INCORRECT_ASC_FRAME, 				{ALARM_SUBCAT,"AC Incorrect ASC Frame","AC Incorrect ASC Frame is received","N/A"}},
	{ALARM_ELC_ASC_TIMEOUT, 						{ALARM_SUBCAT,"AC ASC Communication Timeout","AC ASC Communication Timeout is detected","N/A"}},
	{ALARM_ELC_GDS_ACTIVE_POWERUP, 					{ALARM_SUBCAT,"AC GDS Active Power Up","AC GDS signal is active during Power Up","N/A"}},
	{ALARM_ELC_ULS_INACTIVE_POWERUP, 				{ALARM_SUBCAT,"AC ULS Inactive during Power Up","AC ULS signal is inactive during Power Up","N/A"}},
	{ALARM_ELC_TRS_ACTIVE_POWERUP, 					{ALARM_SUBCAT,"AC TRS Active during Power Up","AC TRS signal is active during Power Up","N/A"}},
	{ALARM_ELC_ULS_INACTIVE_READY, 					{ALARM_SUBCAT,"AC ULS Inactive during Ready","AC ULS siganl is inactive during Ready","N/A"}},
	{ALARM_ELC_FAIL24V_ACTIVE_READY, 				{ALARM_SUBCAT,"AC Fail24V Active during Ready","AC Fail24V siganl is active during Ready","N/A"}},
	{ALARM_ELC_GDS_ACTIVE_READY, 					{ALARM_SUBCAT,"AC GDS Active during Ready","AC GDS signal is active during Ready","N/A"}},
	{ALARM_ELC_TRS_ACTIVE_READY, 					{ALARM_SUBCAT,"AC TRS Active during Ready","AC TRS signal is active during Ready","N/A"}},
	{ALARM_ELC_FAIL24V_ACTIVE_DOWNSTROKE, 			{ALARM_SUBCAT,"AC Fail24V Active during Downstroke","AC Fail24V signal is active during Downstroke","N/A"}},
	{ALARM_ELC_GDS_ACTIVE_DOWNSTROKE, 				{ALARM_SUBCAT,"AC GDS Active during Downstroke","AC GDS signal is active during Downstroke","N/A"}},
	{ALARM_ELC_FAIL24V_ACTIVE_RETURNSTROKE, 		{ALARM_SUBCAT,"AC Fail24V Active during Return Stroke","AC Fail24V signal is active during Return Stroke","N/A"}},
	{ALARM_ELC_GDS_ACTIVE_RETURNSTROKE, 			{ALARM_SUBCAT,"AC GDS Active during Return Stroke","AC GDS signal is active during Return Stroke","N/A"}},
	{ALARM_ELC_ULS_ACTIVE_HOLD, 					{ALARM_SUBCAT,"AC ULS Active during Hold","AC ULS signal is active during Hold","N/A"}},
	{ALARM_ELC_FAIL24V_ACTIVE_HOLD, 				{ALARM_SUBCAT,"AC Fail24V Active during Hold","AC Fail24V signal is active during Hold","N/A"}},
	{ALARM_ELC_GDS_ACTIVE_HOLD, 					{ALARM_SUBCAT,"AC GDS Active during Hold","AC GDS signal is active during Hold","N/A"}},

	{REMINDER_1, 	{REMINDER_SUBCAT,"Reminder 1","N/A","N/A"}},
	{REMINDER_2, 	{REMINDER_SUBCAT,"Reminder 2","N/A","N/A"}},
	{REMINDER_3, 	{REMINDER_SUBCAT,"Reminder 3","N/A","N/A"}},	
	{REMINDER_4, 	{REMINDER_SUBCAT,"Reminder 4","N/A","N/A"}},
	{REMINDER_5, 	{REMINDER_SUBCAT,"Reminder 5","N/A","N/A"}},
	{REMINDER_6, 	{REMINDER_SUBCAT,"Reminder 6","N/A","N/A"}},
	{REMINDER_7, 	{REMINDER_SUBCAT,"Reminder 7","N/A","N/A"}},	
	{REMINDER_8, 	{REMINDER_SUBCAT,"Reminder 8","N/A","N/A"}},
	{REMINDER_9, 	{REMINDER_SUBCAT,"Reminder 9","N/A","N/A"}},
	{REMINDER_10, 	{REMINDER_SUBCAT,"Reminder 10","N/A","N/A"}},
};
