/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------
    ScanGraphData.h file provides graph backend data.

--------------------------- REVISION HISTORY ------------------------------
 rev1: 03/04/2024 - Initial version.
***************************************************************************/
#ifndef SCANGRAPHDATA_H
#define SCANGRAPHDATA_H

#include <QObject>
#include <QTextStream>
#include <QtCharts/QAbstractSeries>
#include <QtCharts/QAreaSeries>
#include <QtQuick/QQuickView>
#include <QtQuick/QQuickItem>
#include <QtCore/QtMath>
#include <QFile>
#include <QQmlContext>
#include <QDateTime>
#include <QTime>
#include "GraphAxisDef.h"
#include "qrandom.h"
#include <QtCharts/QXYSeries>
//#include "ScanSignatureAce.h"
#include "ScanCycleDetailsListModel.h"

class ScanGraphData : public QObject
{
    Q_OBJECT

public:
    ~ScanGraphData();
public:
    explicit ScanGraphData(QObject *parent = nullptr);
    Q_INVOKABLE int appendSamples(QAbstractSeries* a_series, quint8 a_type);

    Q_INVOKABLE void setAxisMinParameters(QList<qreal> &a_axisVal);
    Q_INVOKABLE void setAxisMaxParameters(QList<qreal> &a_axisVal);

    Q_INVOKABLE QList<qreal> getAxisMinParameters();
    Q_INVOKABLE QList<qreal> getAxisMaxParameters();

    Q_INVOKABLE void clearGraph();
    Q_INVOKABLE void initiateScanGraphSignature(int CycleCountValue, bool Value);
    Q_INVOKABLE bool isRequestedScanSignatureDataAvailable(void);
    Q_INVOKABLE void requestSelectedCycleNo(int Value);
    Q_INVOKABLE bool isEmptyScanSignatureReceived();

private:
    inline void calculateLargest(qreal &a_axisVal , qreal a_val);
    inline void calculateSmallest(qreal &a_axisVal , qreal a_val);
    void receiveScanGraphData();

    int m_GraphPointsCount;
    QVector<QPointF> m_FreqPoints ;
    QVector<QPointF> m_AmpPoints;
    QVector<QPointF> m_CurrPoints;
    QVector<QPointF> m_PhasPoints;

    /* Axis Parameters */
    QList<qreal> m_AxisMinParameters;
    QList<qreal> m_AxisMaxParameters;

    int m_ActiveWelderId = -1;
    HornScanSignature *m_ScanSignature;
//    ScanSignatureACE *m_ScanSignatureACE;

//    ScanCycleDetailsListModel m_ScanCycleDetailsListModel;

    /*Holds Requested Scan Signature Data*/
    std::deque<HornScanSignatureStruct> m_ScanSignatureData;
    pthread_mutex_t mtx;

    bool  m_IsRequestedScanSignatureDataAvailable;
    int   m_RequestSelectedCycleNo;
    float m_RequestSelectedTriggerPoint;
    float m_RequestSelectedScanSonicPoint;
    float m_RequestSelectedHoldPoint;
    bool  m_IsLatestScanSignatureReadRequest;
    bool  m_IsCycleCountScanSignatureReadRequest;
    bool  m_IsEmptyScanSignatureReceived;

    /*Signals used to notify qml screen*/
signals:
    void updateGraphInitiated();
    void updateGraphAvailable();
    void initiateScanGraphSignatureSettings(HornScanSignature *m_ScanSignature);

    /*Slot to be called when data update signal generated by communication thread*/
private slots:
    void OnScanSignatureUpdated(HornScanSignature *DiagnosticsScanSignatureScreen_Obj, int WelderId);
};

#endif // SCANGRAPHDATA_H
