/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------
    SeekGraphData.h file provides graph backend data.

--------------------------- REVISION HISTORY ------------------------------
 rev1: 12/03/2024 - Initial version.
***************************************************************************/
#ifndef SEEKGRAPHDATA_H
#define SEEKGRAPHDATA_H

#include <QObject>
#include <QTextStream>
#include <QtCharts/QAbstractSeries>
#include <QtCharts/QAreaSeries>
#include <QtQuick/QQuickView>
#include <QtQuick/QQuickItem>
#include <QtCore/QtMath>
#include <QFile>
#include <QQmlContext>
#include <QDateTime>
#include <QTime>
#include "GraphAxisDef.h"
#include <QtCharts/QXYSeries>
#include "SeekSignature.h"
#include "Seek.h"

class SeekGraphData : public QObject
{
    Q_OBJECT

public:
    ~SeekGraphData();
public:
    explicit SeekGraphData(QObject *parent = nullptr);
    Q_INVOKABLE int appendSamples(QAbstractSeries* a_series, quint8 a_type);

    Q_INVOKABLE void setAxisMinParameters(QList<qreal> &a_axisVal);
    Q_INVOKABLE void setAxisMaxParameters(QList<qreal> &a_axisVal);

    Q_INVOKABLE QList<qreal> getAxisMinParameters();
    Q_INVOKABLE QList<qreal> getAxisMaxParameters();

    Q_INVOKABLE void clearGraph();
    Q_INVOKABLE void initiateSeekGraphSignature(bool Value);
    Q_INVOKABLE bool isRequestedSeekSignatureDataAvailable(void);
    Q_INVOKABLE bool isEmptySeekSignatureReceived();
    Q_INVOKABLE void isScreenReNavigated(bool Value);

private:
    inline void calculateLargest(qreal &a_axisVal , qreal a_val);
    inline void calculateSmallest(qreal &a_axisVal , qreal a_val);
    void receiveSeekGraphData();

    int m_GraphPointsCount;
    QVector<QPointF> m_TimePoints ;
    QVector<QPointF> m_FreqPoints ;
    QVector<QPointF> m_PowerPoints ;
    QVector<QPointF> m_AmpPoints;
    QVector<QPointF> m_CurrPoints;
    QVector<QPointF> m_PhasPoints;

    /* Axis Parameters */
    QList<qreal> m_AxisMinParameters ;
    QList<qreal> m_AxisMaxParameters;

    int m_ActiveWelderId = -1;
    bool m_IsScreenReNavigated = false;

    SeekSignature *m_SeekSignature;
    Seek m_Seek;

    /*Holds Requested seek Signature Data*/
    std::deque<SeekSignatureStruct> m_RequestedSeekSignatureData;
    pthread_mutex_t mtx;

    bool  m_IsRequestedSeekSignatureDataAvailable;
    bool  m_IsLatestSeekSignatureReadRequest;
    bool  m_IsEmptySeekSignatureReceived;

    /*Signals used to notify qml screen*/
signals:
    void updateGraphInitiated();
    void updateGraphAvailable();
    void initiateSeekGraphSignatureSettings(SeekSignature *m_SeekSignature);

    /*Slot to be called when data update signal generated by communication thread*/
private slots:
    void OnSeekSignatureUpdated(SeekSignature *DiagnosticsSeekSignatureScreen_Obj, int WelderId);
};

#endif // SEEKGRAPHDATA_H
