/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------
    TestGraphData.h file provides graph backend data.

--------------------------- REVISION HISTORY ------------------------------
 rev1: 12/03/2024 - Initial version.
***************************************************************************/
#ifndef TESTGRAPHDATA_H
#define TESTGRAPHDATA_H

#include <QObject>
#include <QTextStream>
#include <QtCharts/QAbstractSeries>
#include <QtCharts/QAreaSeries>
#include <QtQuick/QQuickView>
#include <QtQuick/QQuickItem>
#include <QtCore/QtMath>
#include <QFile>
#include <QQmlContext>
#include <QDateTime>
#include <QTime>
#include "GraphAxisDef.h"
#include <QtCharts/QXYSeries>
#include "TestSignature.h"
#include "Test.h"

class TestGraphData : public QObject
{
    Q_OBJECT

public:
    ~TestGraphData();
public:
    explicit TestGraphData(QObject *parent = nullptr);
    Q_INVOKABLE int appendSamples(QAbstractSeries* a_series, quint8 a_type);

    Q_INVOKABLE void setAxisMinParameters(QList<qreal> &a_axisVal);
    Q_INVOKABLE void setAxisMaxParameters(QList<qreal> &a_axisVal);

    Q_INVOKABLE QList<qreal> getAxisMinParameters();
    Q_INVOKABLE QList<qreal> getAxisMaxParameters();

    Q_INVOKABLE void clearGraph();
    Q_INVOKABLE void initiateTestGraphSignature(bool Value);
    Q_INVOKABLE bool isRequestedTestSignatureDataAvailable();
    Q_INVOKABLE bool isEmptyTestSignatureReceived();
    Q_INVOKABLE void isScreenReNavigated(bool Value);

private:
    inline void calculateLargest(qreal &a_axisVal , qreal a_val);
    inline void calculateSmallest(qreal &a_axisVal , qreal a_val);
    void receiveTestGraphData();

    int m_GraphPointsCount;
    QVector<QPointF> m_TimePoints ;
    QVector<QPointF> m_FreqPoints ;
    QVector<QPointF> m_PowerPoints ;
    QVector<QPointF> m_AmpPoints;
    QVector<QPointF> m_CurrPoints;
    QVector<QPointF> m_PhasPoints;

    /* Axis Parameters */
    QList<qreal> m_AxisMinParameters ;
    QList<qreal> m_AxisMaxParameters;

    int m_ActiveWelderId = -1;
    bool m_IsScreenReNavigated = false;

    TestSignature *m_TestSignature;
    Test m_Test;

    /*Holds Requested test Signature Data*/
    std::deque<TestSignatureStruct> m_RequestedTestSignatureData;
    pthread_mutex_t mtx;

    bool  m_IsRequestedTestSignatureDataAvailable;
    bool  m_IsLatestTestSignatureReadRequest;
    bool  m_IsEmptyTestSignatureReceived;

    /*Signals used to notify qml screen*/
signals:
    void updateGraphInitiated();
    void updateGraphAvailable();
    void initiateTestGraphSignatureSettings(TestSignature *m_TestSignature);

    /*Slot to be called when data update signal generated by communication thread*/
private slots:
    void OnTestSignatureUpdated(TestSignature *DiagnosticsTestSignatureScreen_Obj, int WelderId);
};

#endif // TESTGRAPHDATA_H
