/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------
    CalibrateQuick.h file handles calibration related operations.
--------------------------- REVISION HISTORY ------------------------------
    rev1: 18/10/2024 - Initial version.
***************************************************************************/
#ifndef CALIBRATEQUICK_H
#define CALIBRATEQUICK_H

#include <QObject>
#include "UpdateScreens.h"

class CalibrateQuick : public QObject
{
    /*Q_PROPERTY macro is used for declaring properties in classes that inherit QObject.
      Properties behave like class data members, but they have additional features accessible through the Meta-Object System.*/
    Q_OBJECT

public:

    explicit CalibrateQuick(QObject *parent = nullptr);
    ~CalibrateQuick();

    Q_INVOKABLE void isScreenReNavigated(bool Value);


private:
    bool m_IsScreenReNavigated;
    int m_ActiveWelderId = -1;

    CalibrationAce *m_CalibrationAce;

    pthread_mutex_t mtx;

    /*Signals used to notify qml screen*/
signals:
    void partContactDetected();

    /*Slot to be called when data update signal generated by communication thread*/
private slots:
    void OnCalibrateQuickUpdated(CalibrationAce *CalibrationAce_Obj, int WelderId);
};
#endif // CALIBRATEQUICK_H
