/**************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

---------------------------- MODULE DESCRIPTION ----------------------------
    CalibrateActuator.h file handles calibration related operations.
--------------------------- REVISION HISTORY ------------------------------
    rev1: 18/10/2024 - Initial version.
***************************************************************************/
#ifndef CALIBRATEACTUATOR_H
#define CALIBRATEACTUATOR_H

#include <QObject>
#include "UpdateScreens.h"

class CalibrateActuator : public QObject
{
    /*Q_PROPERTY macro is used for declaring properties in classes that inherit QObject.
      Properties behave like class data members, but they have additional features accessible through the Meta-Object System.*/
    Q_OBJECT

public:
    explicit CalibrateActuator(QObject *parent = nullptr);
    ~CalibrateActuator();

    Q_INVOKABLE void isScreenReNavigated(bool Value);
    Q_INVOKABLE void onQuickCalibrationPressed();



private:
    bool m_IsScreenReNavigated;
    int m_ActiveWelderId = -1;
    float m_CalibrationReadings;

    CalibrationAce *m_CalibrationAce;

    pthread_mutex_t mtx;

    /*Signals used to notify qml screen*/
signals:


    /*Slot to be called when data update signal generated by communication thread*/
private slots:
    void OnCalibrateActuatorUpdated(CalibrationAce *CalibrationAce_Obj, int WelderId);
};
#endif // CALIBRATEACTUATOR_H
