/**************************************************************************

         Copyright (c) Branson Ultrasonics Corporation, 1996-2023

         This program is the property of Branson Ultrasonics Corporation
         Copying of this software is expressly forbidden, without the prior
         written consent of Branson Ultrasonics Corporation.

--------------------------- MODULE DESCRIPTION ----------------------------

 Declares SystemFeature class which is responsible to do interaction between frontend and backend .

--------------------------- REVISION HISTORY ------------------------------
 rev1: 27-03-2025

***************************************************************************/
#ifndef SYSTEMFEATURE_H
#define SYSTEMFEATURE_H

#include <QObject>
#include "ConfigUtilityVersion.h"

class SystemFeature : public QObject
{
    Q_OBJECT
    Q_PROPERTY(int storageType READ getstorageType NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int eventLogging READ getEventLogging NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int batchControl READ getBatchControl NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int userAccessLevel READ getUserAccessLevel NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int barcodeScanner READ getBarcodeScanner NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int userIODiagnostics READ getUserIODiagnostics NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int ldap READ getLdap NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int industrialEthernet READ getIndustrialEthernet NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int pcUtility READ getpcUtility NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(int HMIType READ getHMIType NOTIFY onSystemInfoDataChanged)
    Q_PROPERTY(QString ConfigurationVersion READ getConfigurationVersion NOTIFY systemConfigVersionUpdated)

public:
    explicit SystemFeature(QObject *parent = nullptr);
    int getstorageType() const;
    int getEventLogging() const;
    int getBatchControl() const;
    int getUserAccessLevel() const;
    int getBarcodeScanner() const;
    int getUserIODiagnostics() const;
    int getLdap() const;
    int getIndustrialEthernet() const;
    int getpcUtility() const;
    int getHMIType()const;
    QString getConfigurationVersion() const;

signals:
    void onSystemInfoDataChanged();
    void systemConfigVersionUpdated();

private:
    int m_bearingType;
    int m_HMIType;
    int m_WelderId = -1;

    ConfigUtilityVersion *m_ConfigUtilityVersion;
    QString m_ConfigurationVersion;

private slots:
    /*Slot to be called when data update signal generated by communication thread*/
    void OnConfigVersionScreenUpdated(ConfigUtilityVersion *ConfigUtilityVersionData_Obj, int WelderId);
};


#endif // SYSTEMFEATURE_H
