/**********************************************************************************************************

      Copyright (c) Branson Ultrasonics Corporation, 1996-2023

     This program is the property of Branson Ultrasonics Corporation
     Copying of this software is expressly forbidden, without the prior
     written consent of Branson Ultrasonics Corporation.

 ---------------------------- MODULE DESCRIPTION ----------------------------
 
 This file contains UISCREEN enum where enumerator for each screen is defined .
 
 **********************************************************************************************************/

#ifndef UISCREENDEF_H
#define UISCREENDEF_H
#include <QObject>
#include <QQmlEngine>

#define UISCREENENUM_URI_NAME "Com.Branson.UIScreenEnum"
#define UISCREENENUM_QML_MAJOR_VERSION 1
#define UISCREENENUM_QML_MINOR_VERSION 0
#define UISCREENENUM_QML_NAME "UIScreenEnum"

//UIScreenEnum class contains declaration of enumerator for each screen.
class UIScreenEnum : public QObject
{
    Q_OBJECT
    Q_ENUMS(UISCREEN)
public:
    enum UISCREEN
    {
        NONESCREEN = -1,
        LOGIN = 0,
        FIRST_TIME_LOGIN_CHANGE_PASSWORD,
        DASHBOARD,
        LEFTMENU,
        RIGHTMENU,
        RECIPES,
        RECIPES_LAB,
        RECIPES_LAB_SETTING,
        RECIPES_LAB_WELDMODE,
        RECIPES_LAB_WELDPROCESS,
        RECIPES_LAB_WELDPROCESS_PRETRIGGER,
        RECIPES_LAB_WELDPROCESS_AFTERBURST,
        RECIPES_LAB_PARAMETERA2Z,
        RECIPES_LAB_LIMITS,
        RECIPES_LAB_LIMITS_SETUP,
        RECIPES_LAB_LIMITS_CONTROL,
        RECIPES_LAB_LIMITS_SUSPECT_REJECT,
        RECIPES_LAB_LIMITS_ENERGY_COMPENSATION,
        RECIPES_LAB_STACKRECIPE,
        RECIPES_LAB_RESULTVIEW,
        RECIPES_LAB_GRAPHSETTING,
        RECIPES_LAB_BATCH_SETTING,
        WELDMODE_VALUE_LOWERSTRING,
        PRODUCTION,
        ANALYTICS,
        ANALYTICS_RESULT_GRAPH_VIEW,
        ANALYTICS_RESULT_TABLE_VIEW,
        ANALYTICS_RESULT_GRAPH_VIEW_CYCLE_DETAILS_LIST,
        ANALYTICS_RESULT_GRAPH_RIGHT_SETTING,
        ANALYTICS_RESULT_GRAPH_HEADER_SETTING,
        ANALYTICS_RESULT_GRAPH_AXIS,
        SYSTEM,
        SYSTEM_INFO,
        SYSTEM_CONFIG,
        SYSTEM_CONFIG_GENERAL,
        SYSTEM_CONFIG_USERMANAGEMENT,
        SYSTEM_CONFIG_USER_LIST_RESET_PASSWORD,
        SYSTEM_CONFIG_USER_LIST_CHANGE_PASSWORD,
        SYSTEM_CONFIG_LDAP_CONFIG,
        SYSTEM_CONFIG_USERMANAGEMENT_GLOBAL_USER_SETTINGS,
        SYSTEM_CONFIG_USERMANAGEMENT_ADD_USER,
        SYSTEM_CONFIG_GATEWAY_DATA,
        SYSTEM_CONFIG_USERIO,
        SYSTEM_CONFIG_USERIO_POWERIO,
        SYSTEM_CONFIG_USERIO_POWERIO_DIGITALIO,
        SYSTEM_CONFIG_USERIO_POWERIO_ANALOGIO,
        SYSTEM_CONFIG_USERIO_POWERIO_INDUSTRIAL,
        SYSTEM_CONFIG_USERIO_ACTUATORIO,
        SYSTEM_CONFIG_NETWORKCONFIGURATION,
        SYSTEM_CONFIG_NETWORKCONFIGURATION_NFS,
        SYSTEM_CONFIG_NETWORKCONFIGURATION_ETHERNETIP,
        SYSTEM_CONFIG_NETWORKCONFIGURATION_PROFINET,
        SYSTEM_CONFIG_ALARMMANGEMENT,
        SYSTEM_CONFIG_USB_AUTHENTICATION,
        SYSTEM_DATA,
        BRANSON_SYSTEM_CONFIGURATION,
        BRANSON_SERVICE_TAB,
        SYSTEM_SOFTWARE_UPGRADE,
        SYSTEM_SOFTWARE_UPGRADE_WELDER,
        SYSTEM_SOFTWARE_UPGRADE_RASPPI,
        SYSTEM_SERVICE_COUNT,
        SYSTEM_CALIBRATE,
        SYSTEM_CALIBRATE_ACTUATOR,
        SYSTEM_CALIBRATE_ACTUATOR_WITH_START_SWITCHES,
        SYSTEM_CALIBRATE_FULL_SYSTEM,
        SYSTEM_CALIBRATE_FORCE,
        SYSTEM_CALIBRATE_PRESSURE,
        SYSTEM_CALIBRATE_RESET_SENSORS,
        SYSTEM_CALIBRATE_SENSORS,
        ACTUATORSETUP,
        DIAGNOSTICS,
        DIAGNOSTICS_SCAN,
        DIAGNOSTICS_SCAN_RECIPE,
        DIAGNOSTICS_SCAN_CYCLE_DETAILS_LIST,
        DIAGNOSTICS_SCAN_GRAPH_VIEW,
        DIAGNOSTICS_TEST,
        DIAGNOSTICS_TEST_RECIPE,
        DIAGNOSTICS_TEST_GRAPH_VIEW,
        DIAGNOSTICS_SEEK,
        DIAGNOSTICS_SEEK_RECIPE,
        DIAGNOSTICS_SEEK_GRAPH_VIEW,
        DIAGNOSTICS_EVENT,
        DIAGNOSTICS_ALARM,
        DIAGNOSTIC_USERIO,
        IMPORTEXPORT,
        GENERATEREPORT,
        GENERATE_REPORT,
        GENERATE_REPORT_STORAGE,
        GENERATE_REPORT_DATA_FILTERS,
        GENERATE_REPORT_SUMMARY,
        GENERATE_REPORT_CONTINUOUS_STORAGE,
        GENERATE_REPORT_CONTINUOUS_DATA_FILTER,
        GENERATE_REPORT_CONTINUOUS_SUMMARY,
        GENERATE_REPORT_POPUP,
        LANGUAGE,
        LOGOUT,
        EXIT,
        NUMPAD,
        SELECTLANGUAGE,
		ALARM,
        ALARM_GENERAL,
        ALARM_NAME,
        ALARM_DESCRIPTION,
        POPUP,
        MULTIWELDERINFORMATION,
        PLATFORM_CONFIG,
        FOOTER,
        PLATFORM_CONFIG_UPGRADE,
        PLATFORM_CONFIG_UPGRADE_START_USB,
        PLATFORM_CONFIG_UPGRADE_START_ETH,
        PLATFORM_CONFIG_UPGRADE_READ_USB,
        PLATFORM_CONFIG_UPGRADE_READ_ETH,
        PLATFORM_CONFIG_UPGRADE_USB,
        PLATFORM_CONFIG_UPGRADE_ETHERNET,
        PLATFORM_CONFIG_UPGRADE_INTERFACE,
        ALERTWINDOW,
        MESSAGEPOPUP,
        ALARMEVENTSLOG,
        CONFIRMATION_POPUP,
        ESTOP_POPUP
    };

    static void registerQMLType()
    {
        qmlRegisterType<UIScreenEnum>(UISCREENENUM_URI_NAME,
                                       UISCREENENUM_QML_MAJOR_VERSION,
                                       UISCREENENUM_QML_MINOR_VERSION,
                                       UISCREENENUM_QML_NAME);
    }
};
#endif // UISCREENDEF_H
